"""initial_schema

Revision ID: 134985c7a638
Revises: 
Create Date: 2026-04-03 20:17:37.578410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134985c7a638'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('reports_per_month_limit', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('dijbekero_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('amount_huf', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dijbekero_presets_id'), 'dijbekero_presets', ['id'], unique=False)
    op.create_table('dijbekero_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('marketing_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_subscribers_email'), 'marketing_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_marketing_subscribers_id'), 'marketing_subscribers', ['id'], unique=False)
    op.create_table('pending_checkout_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_checkout_passwords_id'), 'pending_checkout_passwords', ['id'], unique=False)
    op.create_index(op.f('ix_pending_checkout_passwords_stripe_session_id'), 'pending_checkout_passwords', ['stripe_session_id'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('reports_per_month_limit', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('plan_key')
    )
    op.create_table('pending_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('amount_huf', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('buyer_zip', sa.String(), nullable=True),
    sa.Column('buyer_city', sa.String(), nullable=True),
    sa.Column('buyer_address', sa.String(), nullable=True),
    sa.Column('buyer_tax_number', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_orders_email'), 'pending_orders', ['email'], unique=False)
    op.create_index(op.f('ix_pending_orders_id'), 'pending_orders', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('report_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('signature_path', sa.String(), nullable=True),
    sa.Column('pfx_path', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('hrsz', sa.String(), nullable=True),
    sa.Column('building_purpose', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('instrument_type', sa.String(), nullable=True),
    sa.Column('instrument_cal', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectors_id'), 'inspectors', ['id'], unique=False)
    op.create_index(op.f('ix_inspectors_name'), 'inspectors', ['name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('amount_huf', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('pending_order_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pending_order_id'], ['pending_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_logs_email'), 'payment_logs', ['email'], unique=False)
    op.create_index(op.f('ix_payment_logs_id'), 'payment_logs', ['id'], unique=False)
    op.create_table('registration_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_invites_email'), 'registration_invites', ['email'], unique=False)
    op.create_index(op.f('ix_registration_invites_id'), 'registration_invites', ['id'], unique=False)
    op.create_index(op.f('ix_registration_invites_token_hash'), 'registration_invites', ['token_hash'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('company_shared', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspector_notes', sa.Text(), nullable=True),
    sa.Column('client_data', sa.JSON(), nullable=True),
    sa.Column('diagram_data', sa.JSON(), nullable=True),
    sa.Column('diagram_image', sa.Text(), nullable=True),
    sa.Column('floor_plan_image', sa.Text(), nullable=True),
    sa.Column('defects_data', sa.JSON(), nullable=True),
    sa.Column('measurements_data', sa.JSON(), nullable=True),
    sa.Column('incoming_phases', sa.JSON(), nullable=True),
    sa.Column('note_photos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.create_table('report_share_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_share_tokens_id'), 'report_share_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_report_share_tokens_report_id'), 'report_share_tokens', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_share_tokens_token'), 'report_share_tokens', ['token'], unique=True)
    op.create_table('site_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('collapsed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['site_nodes.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_nodes_report_id'), 'site_nodes', ['report_id'], unique=False)
    op.create_table('meas_insulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('ln', sa.String(), nullable=True),
    sa.Column('lpe', sa.String(), nullable=True),
    sa.Column('npe', sa.String(), nullable=True),
    sa.Column('pass_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['site_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meas_insulation_id'), 'meas_insulation', ['id'], unique=False)
    op.create_table('meas_loop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('zs', sa.String(), nullable=True),
    sa.Column('pass_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['site_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meas_loop_id'), 'meas_loop', ['id'], unique=False)
    op.create_table('meas_rcd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('idn', sa.String(), nullable=True),
    sa.Column('test_05', sa.String(), nullable=True),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t5', sa.String(), nullable=True),
    sa.Column('ramp', sa.String(), nullable=True),
    sa.Column('uc', sa.String(), nullable=True),
    sa.Column('pass_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['site_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meas_rcd_id'), 'meas_rcd', ['id'], unique=False)
    op.create_table('meas_rpe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('point', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('val', sa.String(), nullable=True),
    sa.Column('pass_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['site_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meas_rpe_id'), 'meas_rpe', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meas_rpe_id'), table_name='meas_rpe')
    op.drop_table('meas_rpe')
    op.drop_index(op.f('ix_meas_rcd_id'), table_name='meas_rcd')
    op.drop_table('meas_rcd')
    op.drop_index(op.f('ix_meas_loop_id'), table_name='meas_loop')
    op.drop_table('meas_loop')
    op.drop_index(op.f('ix_meas_insulation_id'), table_name='meas_insulation')
    op.drop_table('meas_insulation')
    op.drop_index(op.f('ix_site_nodes_report_id'), table_name='site_nodes')
    op.drop_table('site_nodes')
    op.drop_index(op.f('ix_report_share_tokens_token'), table_name='report_share_tokens')
    op.drop_index(op.f('ix_report_share_tokens_report_id'), table_name='report_share_tokens')
    op.drop_index(op.f('ix_report_share_tokens_id'), table_name='report_share_tokens')
    op.drop_table('report_share_tokens')
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_registration_invites_token_hash'), table_name='registration_invites')
    op.drop_index(op.f('ix_registration_invites_id'), table_name='registration_invites')
    op.drop_index(op.f('ix_registration_invites_email'), table_name='registration_invites')
    op.drop_table('registration_invites')
    op.drop_index(op.f('ix_payment_logs_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_email'), table_name='payment_logs')
    op.drop_table('payment_logs')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_inspectors_name'), table_name='inspectors')
    op.drop_index(op.f('ix_inspectors_id'), table_name='inspectors')
    op.drop_table('inspectors')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pending_orders_id'), table_name='pending_orders')
    op.drop_index(op.f('ix_pending_orders_email'), table_name='pending_orders')
    op.drop_table('pending_orders')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_pending_checkout_passwords_stripe_session_id'), table_name='pending_checkout_passwords')
    op.drop_index(op.f('ix_pending_checkout_passwords_id'), table_name='pending_checkout_passwords')
    op.drop_table('pending_checkout_passwords')
    op.drop_index(op.f('ix_marketing_subscribers_id'), table_name='marketing_subscribers')
    op.drop_index(op.f('ix_marketing_subscribers_email'), table_name='marketing_subscribers')
    op.drop_table('marketing_subscribers')
    op.drop_table('dijbekero_sequences')
    op.drop_index(op.f('ix_dijbekero_presets_id'), table_name='dijbekero_presets')
    op.drop_table('dijbekero_presets')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
